/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gauss.seidel;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/**
 *
 * @author Salcedo
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCalculate_global = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tabPane_input = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        textField_3X3_a11 = new javax.swing.JTextField();
        textField_3X3_a12 = new javax.swing.JTextField();
        textField_3X3_a13 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textField_3X3_a22 = new javax.swing.JTextField();
        textField_3X3_a23 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textField_3X3_a21 = new javax.swing.JTextField();
        textField_3X3_a32 = new javax.swing.JTextField();
        textField_3X3_a33 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textField_3X3_a31 = new javax.swing.JTextField();
        btnClr_3X3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        textField_3X3_b1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textField_3X3_b2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textField_3X3_b3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        textField_4X4_a11 = new javax.swing.JTextField();
        textField_4X4_a12 = new javax.swing.JTextField();
        textField_4X4_a13 = new javax.swing.JTextField();
        textField_4X4_a14 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textField_4X4_a22 = new javax.swing.JTextField();
        textField_4X4_a23 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        textField_4X4_a21 = new javax.swing.JTextField();
        textField_4X4_a32 = new javax.swing.JTextField();
        textField_4X4_a33 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        textField_4X4_a31 = new javax.swing.JTextField();
        btnClr_3X4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        textField_4X4_b1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        textField_4X4_b2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        textField_4X4_b3 = new javax.swing.JTextField();
        textField_4X4_a41 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        textField_4X4_a42 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        textField_4X4_a43 = new javax.swing.JTextField();
        textField_4X4_a24 = new javax.swing.JTextField();
        textField_4X4_a34 = new javax.swing.JTextField();
        textField_4X4_a44 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        textField_4X4_b4 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea_Output = new javax.swing.JTextArea();
        btnClr_ouputArea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gauss Siedel Method");
        setIconImage(Toolkit.getDefaultToolkit().getImage(GUI.class.getResource("/Icon/calculator.png")));
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("This is an application to solve for systems of Linear Equation Implementing the Gauss -Siedel Method");

        btnCalculate_global.setText("CALCULATE");
        btnCalculate_global.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate_globalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("OUTPUT");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\n\tGauss-Seidel Method is an iterative method to solve for\n\tsystems of linear equations.\n\n\tRelevant Info\n\t1. Make sure that the highest value coefficients are in the diagonal.\n\t2. The calculated values are rounded-off to 5 decimal places.\n\t3. The hard-programmed terminating condition is:\n\t\tEa1 & Ea2 & ... & Ean <= Es; Es=0.00001\n\t4. For this Application, a 3 and 4 dimensional linear equations are\n\tconsidered in creating the GUI.\n\n\t\t\t\t- N . V. S. -");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        );

        tabPane_input.addTab("Main", jPanel1);

        textField_3X3_a11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3X3_a11.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_3X3_a11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_3X3_a11KeyTyped(evt);
            }
        });

        textField_3X3_a12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3X3_a12.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_3X3_a12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_3X3_a12KeyTyped(evt);
            }
        });

        textField_3X3_a13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3X3_a13.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_3X3_a13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_3X3_a13KeyTyped(evt);
            }
        });

        jLabel3.setText("X1 +");

        jLabel4.setText("X2 +");

        textField_3X3_a22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3X3_a22.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_3X3_a22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_3X3_a22KeyTyped(evt);
            }
        });

        textField_3X3_a23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3X3_a23.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_3X3_a23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_3X3_a23KeyTyped(evt);
            }
        });

        jLabel5.setText("X1 +");

        jLabel6.setText("X2 +");

        textField_3X3_a21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3X3_a21.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_3X3_a21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_3X3_a21KeyTyped(evt);
            }
        });

        textField_3X3_a32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3X3_a32.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_3X3_a32.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_3X3_a32KeyTyped(evt);
            }
        });

        textField_3X3_a33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3X3_a33.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_3X3_a33.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_3X3_a33KeyTyped(evt);
            }
        });

        jLabel7.setText("X1 +");

        jLabel8.setText("X2 +");

        textField_3X3_a31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3X3_a31.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_3X3_a31.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_3X3_a31KeyTyped(evt);
            }
        });

        btnClr_3X3.setText("Clear Values");
        btnClr_3X3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClr_3X3ActionPerformed(evt);
            }
        });

        jLabel9.setText("X3 =");

        textField_3X3_b1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3X3_b1.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_3X3_b1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_3X3_b1KeyTyped(evt);
            }
        });

        jLabel10.setText("X3 =");

        textField_3X3_b2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3X3_b2.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_3X3_b2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_3X3_b2KeyTyped(evt);
            }
        });

        jLabel11.setText("X3 =");

        textField_3X3_b3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3X3_b3.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_3X3_b3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_3X3_b3KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textField_3X3_a21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textField_3X3_a22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addGap(11, 11, 11)
                                .addComponent(textField_3X3_a23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField_3X3_b2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textField_3X3_a11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textField_3X3_a12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addGap(11, 11, 11)
                                .addComponent(textField_3X3_a13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField_3X3_b1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(195, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textField_3X3_a31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textField_3X3_a32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(11, 11, 11)
                        .addComponent(textField_3X3_a33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_3X3_b3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClr_3X3)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_3X3_a11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_3X3_a12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_3X3_a13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(textField_3X3_b1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(textField_3X3_b2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textField_3X3_a21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textField_3X3_a22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textField_3X3_a23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(textField_3X3_b3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textField_3X3_a31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textField_3X3_a32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textField_3X3_a33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)))
                .addGap(20, 20, 20)
                .addComponent(btnClr_3X3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        tabPane_input.addTab("3 Equations", jPanel2);

        textField_4X4_a11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_a11.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_a11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_a11KeyTyped(evt);
            }
        });

        textField_4X4_a12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_a12.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_a12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_a12KeyTyped(evt);
            }
        });

        textField_4X4_a13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_a13.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_a13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_a13KeyTyped(evt);
            }
        });

        textField_4X4_a14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_a14.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_a14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_a14KeyTyped(evt);
            }
        });

        jLabel13.setText("X2 +");

        textField_4X4_a22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_a22.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_a22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_a22KeyTyped(evt);
            }
        });

        textField_4X4_a23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_a23.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_a23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_a23KeyTyped(evt);
            }
        });

        jLabel14.setText("X1 +");

        jLabel15.setText("X2 +");

        textField_4X4_a21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_a21.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_a21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_a21KeyTyped(evt);
            }
        });

        textField_4X4_a32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_a32.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_a32.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_a32KeyTyped(evt);
            }
        });

        textField_4X4_a33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_a33.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_a33.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_a33KeyTyped(evt);
            }
        });

        jLabel16.setText("X1 +");

        jLabel17.setText("X2 +");

        textField_4X4_a31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_a31.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_a31.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_a31KeyTyped(evt);
            }
        });

        btnClr_3X4.setText("Clear Values");
        btnClr_3X4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClr_3X4ActionPerformed(evt);
            }
        });

        jLabel18.setText("X4 =");

        textField_4X4_b1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_b1.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_b1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_b1KeyTyped(evt);
            }
        });

        jLabel19.setText("X4 =");

        textField_4X4_b2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_b2.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_b2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_b2KeyTyped(evt);
            }
        });

        jLabel20.setText("X4 =");

        textField_4X4_b3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_b3.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_b3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_b3KeyTyped(evt);
            }
        });

        textField_4X4_a41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_a41.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_a41.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_a41KeyTyped(evt);
            }
        });

        jLabel21.setText("X1 +");

        textField_4X4_a42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_a42.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_a42.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_a42KeyTyped(evt);
            }
        });

        jLabel22.setText("X2 +");

        textField_4X4_a43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_a43.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_a43.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_a43KeyTyped(evt);
            }
        });

        textField_4X4_a24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_a24.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_a24.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_a24KeyTyped(evt);
            }
        });

        textField_4X4_a34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_a34.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_a34.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_a34KeyTyped(evt);
            }
        });

        textField_4X4_a44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_a44.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_a44.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_a44KeyTyped(evt);
            }
        });

        jLabel23.setText("X3 +");

        jLabel24.setText("X3 +");

        jLabel25.setText("X3 +");

        jLabel26.setText("X3 +");

        jLabel27.setText("X4 =");

        textField_4X4_b4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4X4_b4.setPreferredSize(new java.awt.Dimension(50, 50));
        textField_4X4_b4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_4X4_b4KeyTyped(evt);
            }
        });

        jLabel28.setText("X1 +");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textField_4X4_a11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(textField_4X4_a31, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(textField_4X4_a21, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(textField_4X4_a41, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(textField_4X4_a42, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(textField_4X4_a22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(textField_4X4_a12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(textField_4X4_a32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField_4X4_a43, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_4X4_a33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_4X4_a23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_4X4_a13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(12, 12, 12)
                        .addComponent(textField_4X4_a24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(12, 12, 12)
                        .addComponent(textField_4X4_a44, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(12, 12, 12)
                        .addComponent(textField_4X4_a34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(12, 12, 12)
                        .addComponent(textField_4X4_a14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel27)))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField_4X4_b1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_4X4_b3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_4X4_b2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(textField_4X4_b4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnClr_3X4)))
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textField_4X4_a12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textField_4X4_a22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textField_4X4_a32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField_4X4_a33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textField_4X4_a42, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField_4X4_a43, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textField_4X4_a13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textField_4X4_a23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(textField_4X4_b1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textField_4X4_b2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textField_4X4_b3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textField_4X4_b4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnClr_3X4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textField_4X4_a14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textField_4X4_a24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textField_4X4_a34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textField_4X4_a44, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27))))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textField_4X4_a11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textField_4X4_a21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textField_4X4_a31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textField_4X4_a41, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))))
        );

        tabPane_input.addTab("4 Equations", jPanel3);

        textArea_Output.setEditable(false);
        textArea_Output.setColumns(20);
        textArea_Output.setRows(5);
        jScrollPane1.setViewportView(textArea_Output);

        btnClr_ouputArea.setText("CLEAR OUPUT AREA");
        btnClr_ouputArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClr_ouputAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPane_input, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClr_ouputArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalculate_global, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabPane_input)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate_global)
                    .addComponent(btnClr_ouputArea))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculate_globalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate_globalActionPerformed
        // TODO add your handling code here:
        
        //ADD Switch/IF statement
       if(tabPane_input.getSelectedIndex()==1){
           //You are in a 3X3 Matrix situation:
           double[][] aa = new double[4][4];
           double[] x0 = {0,0,0,0};
           double[] results = new double[4];
           double[] bb = new double[4];
           String outputString="";
          try{ 
           aa[1][1]=Double.parseDouble(textField_3X3_a11.getText());
           aa[1][2]=Double.parseDouble(textField_3X3_a12.getText());
           aa[1][3]=Double.parseDouble(textField_3X3_a13.getText());
           aa[2][1]=Double.parseDouble(textField_3X3_a21.getText());
           aa[2][2]=Double.parseDouble(textField_3X3_a22.getText());
           aa[2][3]=Double.parseDouble(textField_3X3_a23.getText());
           aa[3][1]=Double.parseDouble(textField_3X3_a31.getText());
           aa[3][2]=Double.parseDouble(textField_3X3_a32.getText());
           aa[3][3]=Double.parseDouble(textField_3X3_a33.getText());
           
           bb[1]=Double.parseDouble(textField_3X3_b1.getText());
           bb[2]=Double.parseDouble(textField_3X3_b2.getText());
           bb[3]=Double.parseDouble(textField_3X3_b3.getText());
          }
          catch(Exception e){
          textArea_Output.setText("Error! \n"+e);
          }
           
         gaussSeidelMethod m = new gaussSeidelMethod();  
         m.setN(3);
         m.setX(x0);
         m.setA(aa);
         m.setImax(10000);
         m.setEs(0.00001);
         m.setB(bb);
           try {
         results = m.solve();
         outputString+=m.getOutputText();
         outputString+= "\n\n Final results:";
            for(int i =1; i<=results.length-1; i++){
            outputString+="\n x"+i+" = "+results[i];
            }
            textArea_Output.setText(outputString);
           } catch (Exception e) {
            textArea_Output.setText("Error! \n"+e);
           }
         
     
     
       }
       else if(tabPane_input.getSelectedIndex()==2){
            //You are in a 4X4 Matrix situation:
           double[][] aa = new double[5][5];
           double[] x0 = {0,0,0,0,0};
           double[] results = new double[5];
           double[] bb = new double[5];
           String outputString="";
         aa[1][1]=Double.parseDouble(textField_4X4_a11.getText());
         aa[1][2]=Double.parseDouble(textField_4X4_a12.getText());
         aa[1][3]=Double.parseDouble(textField_4X4_a13.getText());
         aa[1][4]=Double.parseDouble(textField_4X4_a14.getText());
         aa[2][1]=Double.parseDouble(textField_4X4_a21.getText());
         aa[2][2]=Double.parseDouble(textField_4X4_a22.getText());
         aa[2][3]=Double.parseDouble(textField_4X4_a23.getText());
         aa[2][4]=Double.parseDouble(textField_4X4_a24.getText());
         aa[3][1]=Double.parseDouble(textField_4X4_a31.getText());
         aa[3][2]=Double.parseDouble(textField_4X4_a32.getText());
         aa[3][3]=Double.parseDouble(textField_4X4_a33.getText());
         aa[3][4]=Double.parseDouble(textField_4X4_a34.getText());
         aa[4][1]=Double.parseDouble(textField_4X4_a41.getText());
         aa[4][2]=Double.parseDouble(textField_4X4_a42.getText());
         aa[4][3]=Double.parseDouble(textField_4X4_a43.getText());
         aa[4][4]=Double.parseDouble(textField_4X4_a44.getText());
         
         bb[1]=Double.parseDouble(textField_4X4_b1.getText());
         bb[2]=Double.parseDouble(textField_4X4_b2.getText());
         bb[3]=Double.parseDouble(textField_4X4_b3.getText());
         bb[4]=Double.parseDouble(textField_4X4_b4.getText());
         
         gaussSeidelMethod m = new gaussSeidelMethod();  
         m.setN(4);
         m.setX(x0);
         m.setA(aa);
         m.setImax(10000);
         m.setEs(0.00001);
         m.setB(bb);
         results = m.solve();
         outputString+=m.getOutputText();
            outputString+= "\n\n Final results:";
            for(int i =1; i<=results.length-1; i++){
            outputString+="\n x"+i+" = "+results[i];
            }
          textArea_Output.setText(outputString);
       } 
       else if(tabPane_input.getSelectedIndex()==3){
       
       }
       else{
       
       }
    }//GEN-LAST:event_btnCalculate_globalActionPerformed

    private void btnClr_ouputAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClr_ouputAreaActionPerformed
        // TODO add your handling code here:
        textArea_Output.setText("");
    }//GEN-LAST:event_btnClr_ouputAreaActionPerformed

    private void btnClr_3X3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClr_3X3ActionPerformed
       clearValues();
    }//GEN-LAST:event_btnClr_3X3ActionPerformed

    private void textField_3X3_a11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_3X3_a11KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_3X3_a11KeyTyped

    private void textField_3X3_a12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_3X3_a12KeyTyped
       char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_3X3_a12KeyTyped

    private void textField_3X3_a13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_3X3_a13KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_3X3_a13KeyTyped

    private void textField_3X3_a21KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_3X3_a21KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_3X3_a21KeyTyped

    private void textField_3X3_a22KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_3X3_a22KeyTyped
      char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_3X3_a22KeyTyped

    private void textField_3X3_a23KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_3X3_a23KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_3X3_a23KeyTyped

    private void textField_3X3_a31KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_3X3_a31KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_3X3_a31KeyTyped

    private void textField_3X3_a32KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_3X3_a32KeyTyped
       char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_3X3_a32KeyTyped

    private void textField_3X3_a33KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_3X3_a33KeyTyped
       char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_3X3_a33KeyTyped

    private void textField_3X3_b1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_3X3_b1KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_3X3_b1KeyTyped

    private void textField_3X3_b2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_3X3_b2KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_3X3_b2KeyTyped

    private void textField_3X3_b3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_3X3_b3KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_3X3_b3KeyTyped

    private void textField_4X4_b4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_b4KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_b4KeyTyped

    private void textField_4X4_a44KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_a44KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_a44KeyTyped

    private void textField_4X4_a34KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_a34KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_a34KeyTyped

    private void textField_4X4_a24KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_a24KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_a24KeyTyped

    private void textField_4X4_a14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_a14KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_a14KeyTyped

    private void textField_4X4_a43KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_a43KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_a43KeyTyped

    private void textField_4X4_a42KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_a42KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_a42KeyTyped

    private void textField_4X4_a41KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_a41KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_a41KeyTyped

    private void textField_4X4_b3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_b3KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_b3KeyTyped

    private void textField_4X4_b2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_b2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL)||c==KeyEvent.VK_MINUS){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_b2KeyTyped

    private void textField_4X4_b1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_b1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_b1KeyTyped

    private void btnClr_3X4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClr_3X4ActionPerformed
    clearValues();
    }//GEN-LAST:event_btnClr_3X4ActionPerformed

    private void textField_4X4_a31KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_a31KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_a31KeyTyped

    private void textField_4X4_a33KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_a33KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_a33KeyTyped

    private void textField_4X4_a32KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_a32KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_a32KeyTyped

    private void textField_4X4_a21KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_a21KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_a21KeyTyped

    private void textField_4X4_a23KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_a23KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_a23KeyTyped

    private void textField_4X4_a22KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_a22KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_a22KeyTyped

    private void textField_4X4_a13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_a13KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_a13KeyTyped

    private void textField_4X4_a12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_a12KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
    }//GEN-LAST:event_textField_4X4_a12KeyTyped

    private void textField_4X4_a11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_4X4_a11KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL||c==KeyEvent.VK_MINUS)){
            evt.consume();
        }
        
    }//GEN-LAST:event_textField_4X4_a11KeyTyped
    private void clearValues(){
        //Clear input TextAreas:
        if(tabPane_input.getSelectedIndex()==1){
        textField_3X3_a11.setText("");
        textField_3X3_a12.setText("");
        textField_3X3_a13.setText("");
        textField_3X3_a21.setText("");
        textField_3X3_a22.setText("");
        textField_3X3_a23.setText("");
        textField_3X3_a31.setText("");
        textField_3X3_a32.setText("");
        textField_3X3_a33.setText(""); 
        
        textField_3X3_b1.setText("");
        textField_3X3_b2.setText("");
        textField_3X3_b3.setText("");
        }
        else if(tabPane_input.getSelectedIndex()==2){
        textField_4X4_a11.setText("");
        textField_4X4_a12.setText("");
        textField_4X4_a13.setText("");
        textField_4X4_a14.setText("");
        textField_4X4_a21.setText("");
        textField_4X4_a22.setText("");
        textField_4X4_a23.setText("");
        textField_4X4_a24.setText("");
        textField_4X4_a31.setText("");
        textField_4X4_a32.setText("");
        textField_4X4_a33.setText("");
        textField_4X4_a34.setText("");
        textField_4X4_a41.setText("");
        textField_4X4_a42.setText("");
        textField_4X4_a43.setText("");
        textField_4X4_a44.setText("");
    }

    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate_global;
    private javax.swing.JButton btnClr_3X3;
    private javax.swing.JButton btnClr_3X4;
    private javax.swing.JButton btnClr_ouputArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTabbedPane tabPane_input;
    private javax.swing.JTextArea textArea_Output;
    private javax.swing.JTextField textField_3X3_a11;
    private javax.swing.JTextField textField_3X3_a12;
    private javax.swing.JTextField textField_3X3_a13;
    private javax.swing.JTextField textField_3X3_a21;
    private javax.swing.JTextField textField_3X3_a22;
    private javax.swing.JTextField textField_3X3_a23;
    private javax.swing.JTextField textField_3X3_a31;
    private javax.swing.JTextField textField_3X3_a32;
    private javax.swing.JTextField textField_3X3_a33;
    private javax.swing.JTextField textField_3X3_b1;
    private javax.swing.JTextField textField_3X3_b2;
    private javax.swing.JTextField textField_3X3_b3;
    private javax.swing.JTextField textField_4X4_a11;
    private javax.swing.JTextField textField_4X4_a12;
    private javax.swing.JTextField textField_4X4_a13;
    private javax.swing.JTextField textField_4X4_a14;
    private javax.swing.JTextField textField_4X4_a21;
    private javax.swing.JTextField textField_4X4_a22;
    private javax.swing.JTextField textField_4X4_a23;
    private javax.swing.JTextField textField_4X4_a24;
    private javax.swing.JTextField textField_4X4_a31;
    private javax.swing.JTextField textField_4X4_a32;
    private javax.swing.JTextField textField_4X4_a33;
    private javax.swing.JTextField textField_4X4_a34;
    private javax.swing.JTextField textField_4X4_a41;
    private javax.swing.JTextField textField_4X4_a42;
    private javax.swing.JTextField textField_4X4_a43;
    private javax.swing.JTextField textField_4X4_a44;
    private javax.swing.JTextField textField_4X4_b1;
    private javax.swing.JTextField textField_4X4_b2;
    private javax.swing.JTextField textField_4X4_b3;
    private javax.swing.JTextField textField_4X4_b4;
    // End of variables declaration//GEN-END:variables

        

}
